Feature: Verify MDM-Schema Validate feature

  @SmokeTest
  Scenario Outline: Verify Error code generated by calling MDM schema APIs
    Given Check Environment "Env"
    Then Create Api "<Api>" with variable "Limit"
    Then Create Body "<Body>" with variable ""
    Then Setup for Api Testing data
    Then Send Request POST
    Then Verify Status code 200
  
    Examples: 
      | Api   | Body   |
      | Api82 | body82 |